---
- name: webserver deploy
  hosts: webservers
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed

    - name: start service
      systemd: 
        name: httpd
        state: started
        enabled: yes
